spring.application.name=course

# nome do nosso perfil de testes no projeto
spring.profiles.active=test
# Permite que o objeto no fim do ciclo de vida
# possa fazer requisições no banco de dados.
# Jackson faz requisições no banco de dados
# quando estiver serializando o json. Alonga o
# ciclo de vida
spring.jpa.open-in-view=true
